config/routes.rb
Rails.application.routes.draw do
  get "user/new"
  get "user/create"
  resource :session
  resources :users, only: [ :new, :create ]
  resources :passwords, param: :token
  resources :products do
    resources :subscribers, only: [ :create ]
  end

  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :subscribers, dependent: :destroy
  has_one_attached :product_image
  has_rich_text :description

  validates :name, presence: true
  validates :inventory_count, numericality: { greater_than_or_equal_to: 0 }

  after_update_commit :notify_subscribers, if: :back_in_stock?

  def back_in_stock?
    inventory_count_previously_was.zero? && inventory_count > 0
  end

  def notify_subscribers
    return unless subscribers.exists?

    subscribers.each do |subscriber|
      ProductMailer.with(product: self, subscriber: subscriber).in_stock.deliver_later
    end
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private

  def authenticated?
    resume_session
  end

  def require_authentication
    resume_session || request_authentication
  end

  def resume_session
    Current.session ||= find_session_by_cookie
  end

  def find_session_by_cookie
    Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
  end

  def request_authentication
    session[:return_to_after_authenticating] = request.url
    redirect_to new_session_path
  end

  def after_authentication_url
    session.delete(:return_to_after_authenticating) || root_url
  end

  def start_new_session_for(user)
    user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
      Current.session = session
      cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
    end
  end

  def terminate_session
    Current.session.destroy
    cookies.delete(:session_id)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[edit update]

  def new; end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit; end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private

  def set_user_by_token
    @user = User.find_by_password_reset_token!(params[:token])
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show]
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.expect(product: [ :name, :description, :product_image, :inventory_count])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[new create]
  rate_limit to: 10, within: 3.minutes, only: :create, with: lambda {
    redirect_to new_session_url, alert: "Try again later."
  }

  def new; end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to root_path
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  allow_unauthenticated_access
  before_action :set_product

  def create
    @product.subscribers.where(subscriber_params).first_or_create
    redirect_to @product, notice: "You are now subscribed."
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def subscriber_params
    params.expect(subscriber: [ :email ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_unauthenticated_access only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice: "User created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= content_for(:title) || "Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <nav class="nav_container">
        <div>
            <%= link_to "Home", root_path %>
        </div>

        <div>
            <%= link_to "Login", new_session_path unless authenticated? %>
        </div>

        <div>
            <%= link_to "Register", new_user_path unless authenticated? %>
        </div>

        <div>
            <%= button_to "Log out", session_path, method: :delete if authenticated? %>
        </div>
    </nav>

    <div class="notice">
        <%= notice %>
    </div>

    <main>
        <%= yield %>
    </main>
</body>

</html>

<style>
    .nav_container {
        display: flex;
        gap: 0.5rem;
    }
</style>

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
<div>
    <%= form.label :name %>
    <%= form.text_field :name %>
</div>
<br>

<div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
</div>
<br>

<div>
    <%= form.label :product_image, style: "display: block" %>
    <%= form.file_field :product_image, accept: "image/*" %>
</div>
<br>

<div>
    <%= form.label :inventory_count, style: "display block" %>
    <%= form.number_field :inventory_count %>
</div>
<br>

<div>
    <span><strong>Actions:</strong></span><br>
    <%= form.submit %>
</div>
<% end %>

app/views/products/_inventory.html.erb
<% if product.inventory_count? %>
<p><%= product.inventory_count %> in stock</p>

<% else %>
<p>Out of stock</p>
<p>Email me when available</p>

<%= form_with model: [product, Subscriber.new] do |form| %>
<%= form.email_field :email, placeholder: "you@example.com", required: true %>
<%= form.submit "Submit" %>
<% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>
<%= link_to "Cancel", @product %>

app/views/products/index.html.erb
<h1>STORE</h1>

<hr />

<% if authenticated? %>
<div>
    <span>
        Para cadastrar um novo produto utilize o link abaixo:
    </span>
    <div>
        <%= link_to "New product", new_product_path if authenticated? %>
    </div>
    <hr />
</div>
<% end %>


<div id="products">
    <h3>Products list:</h3>
    <ul class="product_list">
        <% @products.each do |product| %>
        <li class="product_item">
            <%= product.id %> ->
            <%= link_to product.name, product %>
            <%= product.description %>
            <div class="image_container">
                <%= image_tag product.product_image if product.product_image.attached? %>
            </div>
        </li>
        <% end %>
    </ul>
</div>

<style>
    .product_list {
        display: flex;
        flex-wrap: wrap;
        gap: 1rem;
        list-style: none;
        padding: 0;
    }

    .product_item {
        width: 300px;
        height: 250px;
        border: 1px solid #ddd;
        padding: 10px;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

    .image_container {
        width: 150px;
        height: 150px;
        overflow: hidden;
        display: flex;
        align-items: center;
        justify-content: center;
        border: 1px solid #ccc;
        border-radius: 10px;
        margin: 8px auto auto auto;

        img {
            max-width: 100%;
            max-height: 100%;
            object-fit: cover;
        }
    }
</style>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>
<%= link_to "Cancel", products_path %>

app/views/products/show.html.erb
<% cache @product.cache_key_with_version do %>
<%= render "inventory", product: @product %>

<h1>Product name: <%= @product.name %></h1>
<%= image_tag @product.product_image if @product.product_image.attached? %>

<h2>Product ID: <%= @product.id %></h2>

<div>
    <h3>Description:</h3>
    <p><%= @product.description %></p>
</div>
<% end %>

<hr />

<span><strong>Actions:</strong></span><br />
<div><%= link_to "<- Back", products_path %></div>
<br />

<% if authenticated? %>
<div>> <%= link_to "Edit product", edit_product_path(@product) %></div>
<br />

<div>
    <%= button_to "Delete", @product, method: :delete, data: {turbo_confirm: "Are
  you sure?" } %>
</div>
<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_with model: @user, url: users_path do |form| %>
<div>
    <%= form.label :email_address %>
    <%= form.email_field :email_address %>
</div>

<div>
    <%= form.label :password %>
    <%= form.password_field :password %>
</div>

<div>
    <%= form.label :password_confirmation, "Confirm your password" %>
    <%= form.password_field :password_confirmation %>
</div>

<div>
    <%= form.submit "Register" %>
</div>
<% end %>

<%= link_to "Have an account? Go to login", new_session_path %>